### ISSUE TITLE
Napisat dovod preco chceme niektore properties.

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#1019]
Related to #1006 
Chceme uzivatelom povedat, preco chceme od nich dane udaje.

1 moznost implementacie je pribalit to do userpropkey modelu a potom zobrazovat v user_prop_key forme, alebo additional_registration_forme, pripadne len v tom modal dialogu.

**Comment by dodo42** [comment]
Toto by sa malo vyriešiť v #1154 , keď spíšeme na čo používame osobné údaje, tam môže byť aj špecifikované, keď nejaký seminár pýta, čosi navyše, z akého dôvodu to pýta, rôzne semináre to môžu mať z rôznych dôvodov.
