### ISSUE TITLE
Oznamenie o submite pre veduceho

### ISSUE THREAD

**Issue by black3r** [trojsten/web#1113]
> V FX sa odovzdávajú príklady nepravidelne, a celkom by nám pomohlo ak by pri príklade bol nejaký checkbox, že pri novom submite daného príkladu, by prišiel notifikačný email na adresu zadanú v danom políčku

malo by stacit pridat email field k task modelu (blank=True) a pri submite ak je vyplneny poslat mail (from django.core.mail import send_mail by malo stacit)

**Comment by matuszelenak** [comment]
Síce sa neviem pridať ako assignee z nejakého dôvodu, ale beriem si to.

Otázka na FKSákov : je potrebné vedieť pridať viacero opravovateľov, alebo stačí jeden? Na upravovanie class v admin rozhraní si netrúfam a dávať tam staticky viacero fieldov mi príde škaredé :D

**Comment by dodo42** [comment]
Opravovatelia su vyrieseni tak, ze ku kazdej ulohe sa dl vie zapísať
hocikoho opravovatelov aj recenzentov a pod. Stara sa o to model
TaskPeople. Takže podla mna stačí dať k úlohe chechbox, že chce notifikácie
a maily si uz vies potiahnuť.

Dňa st, 9. máj 2018 17:11 Matúš Zeleňák <notifications@github.com>
napísal(a):

**Comment by mhozza** [comment]
Note: mozno by sme casom chceli mat notifikacie priamo na stranke, s moznostou poslielania emailov pri notifikaciach. Asi na to existuje issue.
