### ISSUE TITLE
Jednoduchý prístup k opraveným úlohám pre riešiteľov

### ISSUE THREAD

**Issue by dodo42** [trojsten/web#1120]
Momentále, aby si riešiteľ pozrel opravené riešenia, musí veľa klikať. Treba sa naklikať k správnej úlohe, čo v prípade starých úloh, kde si nepamätá názov, je dosť nepríjemné. Asi 3 riešitelia sa na to sťažovali.

Bolo by dobré spraviť nejaký dashboard, kde by riešiteľ mal zobrazené všetky jeho odovzdané úlohy. Pre každú úlohy by mal stačiť najnovší submit, k nemu link na zadanie (ním sa vie preliknúť k zadaniu úlohy, kde si vie pozrieť aj staršie submity), body, dátum, komentár, stiahnutie submitu. Tabuľka podobná ako tá pri submitoch jednej úlohy.

Pri väčšine účastníkov sa dajú bez problémov zobraziť úlohy za všetky roky, ale možno by to chcelo nejaké rozdelenie, paging, napr. po rokoch by mohlo byť fajn. Taký extrémista by mohol mať aj 300 úloh odovzdaných.

**Comment by dodo42** [comment]
Spravil som dačo takéto:
![vsetky-ulohy](https://user-images.githubusercontent.com/16623808/39185587-017e840c-47c8-11e8-9485-e37bd2177ed0.png)
Za KMS to takto stačí. Máte o tom nejakú predstavu v KSP / PRASKu? Či tam nejako zobrazovať aj dačo z programov. V ostatných seminároch (pokiaľ viem) každá úloha má len popis.

**Comment by mhozza** [comment]
vyzera fajn, kludne zrob PR.
KSP asi chce rozlisovat medzi popisom a programom.
