### ISSUE TITLE
Notifikácie vedúcim o blížiacich sa deadlinoch

### ISSUE THREAD

**Issue by matuszelenak** [trojsten/web#1160]
Na základe osobných skúseností by som veľmi ocenil nejaké notifikačné emaily pár dní pred deadlinom na zverejnenie zadaní/vzorákov/opravovanie. 

Mohlo by sa to dať togglovať v people pre vedúcich (možno by to časom mohli mať aj účastníci pre koniec série napr? ). Zvlášť by tam mohli byť checkboxy pre deadline zadaní/vzorákov/opravovania.

**Comment by dodo42** [comment]
Nie je na to kalendár, kde si môžeš aj nastaviť, kedy chceš notifikáciu, ktorá každému vie vyhovovať v iný čas. Nedá sa to poriešiť spoločným kalendárom s notifikáciami alebo niečim takým?

**Comment by mhozza** [comment]
Pravdou je, ze stredoskolaci zvycajne nevedia pouzivat kalendar. Ale tiez mame dolezitejsie veci na praci.

**Comment by gardenerik** [comment]
Out of scope, toto by si mal vo svojom záujme riešiť vedúci kola
