### ISSUE TITLE
Dockerfile pre py2

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#1179]
Momentalne mame dockerfile len pre py3, co stazuje testovanie a riesenie issues pre py2, ktore mame na PROD.

V jednom directory ale mozme mat len 1 dockerfile.
Riesenie: vyrobit priecinok docker a v nom podpriecinok py2 a py3 kazdy z vlastnymi docker filami.

Ak by sme v buducnosti to chceli pustat na arm, mozme pridat dalsi py3-arm.

**Comment by black3r** [comment]
Priečinok s Dockerfile fungovať bez hackov nebude, lebo docker štandardne do build kontextu zahŕňa iba veci v priečinku, v ktorom je Dockerfile. 

Čo sa spraviť dá, je mať vedľajšie Dockerfile v jednom directory s hlavným, akurát musia byť pomenované inak, bežne sa zvykáva používať `py2.Dockerfile` alebo `Dockerfile.py2`, potom prípadne doplnkový `docker-compose.py2.yml` a v ňom následne špecifikovať, ktoré Dockerfile má použiť a volať compose s prepínačom `docker-compose -f docker-compose.py2.yml`
