### ISSUE TITLE
Zobrazit rozumnu hlasku ked sa uzivatel snazi submitnut binarku

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#1190]
Python vyhodi UnicodeDecodeError pri enkodovani suboru do utf-8. To skonci 500 pri submitovani.

JudgeClient by to mohol skonvertovat na lepsiu exception, a ta by sa potom v trojstenwebe mala odchitit a skonvertovat na userfriendly message.

**Comment by ano95** [comment]
Testoval som to práve a vyzerá to, že testovač to spokojne zoberie, ale keď posiela protokol späť, nedá sa parsovať - JudgeClient hodí ProtocolCorruptedError, čo spôsobí `PROTCOR` - "Protokol nečitateľný." Asi by mal testovač vrátit niečo zmysluplné, resp. hlásiť, že toto nedokáže testovať.

**Comment by gardenerik** [comment]
takmer duplicate of https://github.com/trojsten/web/issues/628
