### ISSUE TITLE
fabric nefunguje

### ISSUE THREAD

**Issue by maaario** [trojsten/web#1202]
Snažil som sa spraviť dump lokálnej databázy: `fab local dump_sql get_latest_dump`

Ale fab mi nefunguje (Python 2.7.9, Fabric 2.4.0):
```
  File "/home/mario/ksp/trojsten-web/web/fabfile.py", line 4, in <module>
    from fabric.api import env
ImportError: No module named api
```
Asi sa fab nepúšťal pri nejakých posledných updateoch requirements a možno sa v ňom niečo zmenilo.
Buď chceme ťahať staršiu verziu fabricu, alebo upraviť fabfile.

**Comment by mhozza** [comment]
treba starsi fabric, bol v dev requirementoch. Stary vsak nepodporuje py3, takze to casom premigrujem na novy.
