### ISSUE TITLE
Upgrade na django 2+

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#1210]
- Fixnut deprecation warnings (https://github.com/trojsten/web/pull/1209)
- upgradnut incompatible packages
  - wiki na 0.4+ (https://github.com/trojsten/web/pull/1211)
  - :ballot_box_with_check:  ~autoslug (visi na https://github.com/justinmayer/django-autoslug/issues/49, ale mozme zatial ist na master)~

**Comment by justinmayer** [comment]
Hi Michal. I wanted to let you know that django-autoslug v1.9.4, which should now support Django 1.11 and 2.0+, has been [released](https://github.com/justinmayer/django-autoslug/releases/tag/v1.9.4) and [published to PyPI](https://pypi.org/project/django-autoslug/).

Thanks for your patience! 🎉

**Comment by mhozza** [comment]
Great news! Thanks for letting us know Justin!
