### ISSUE TITLE
Fixnut mathjax extension siunitx

### ISSUE THREAD

**Issue by krtko1** [trojsten/web#1212]
Vo [web/base.html](https://github.com/trojsten/web/blob/master/trojsten/templates/trojsten/layout/base.html) treba zmenit zdroj ku siunitx. Ten co tam mame aktualne nepodporuje desatine ciarky. Neviem ci existuje nejaky iny, nenasiel som. Ale [aktualna](https://github.com/burnpanck/MathJax-siunitx/blob/master/siunitx.js) verzia sa zda, ze [funguje](https://rawgit.com/burnpanck/MathJax-siunitx/master/examples/siunitx.dtx.html).

**Comment by ano95** [comment]
Si si istý, že to nefunguje? Práve som testoval na localhoste a tam to vyzerá, že funguje:
![image](https://user-images.githubusercontent.com/11409143/60595624-a41d6580-9da7-11e9-8e6b-f2bc19f1083c.png)

**Comment by krtko1** [comment]
Ide mi o tento prikaz
![2019-07-03-162512_grim](https://user-images.githubusercontent.com/21214184/60599765-4bea6180-9daf-11e9-857f-629844f0aa6f.png)
