### ISSUE TITLE
Neescapovať niektoré HTML tagy v adminovi

### ISSUE THREAD

**Issue by maaario** [trojsten/web#1220]
V adminovi sa (pravdepodobne kvôli updatu Djanga) začali escapovať HTML tagy, ktoré by sa nemali.
Pravdepodobne bude stačiť popozerať nejaké nové verzie funkcií...

Jeden konkrétny nájdený prípad (možno ich bude aj viacero): https://www.ksp.sk/admin/people/user/
V adminovi, keď si zobrazujeme napr. používateľov, tak sa pri nich zobrazujú názvy škôl. Keďže názvy škôl sú dlhé, mali sme to spravené tak, že sa zobrazila iba skratka školy a celý názov sa zobrazil pri hoveri.

**Comment by mhozza** [comment]
Treba but pouzit [format_html](https://docs.djangoproject.com/en/2.1/ref/utils/#django.utils.html.format_html)
alebo [mark_safe](https://docs.djangoproject.com/en/2.1/ref/utils/#django.utils.safestring.mark_safe).

**Comment by mhozza** [comment]
vyzera ze people admin je jediny vyskyt.
