### ISSUE TITLE
Blbý preklad administrácie.

### ISSUE THREAD

**Issue by ano95** [trojsten/web#1270]
"Site administration" = "Registrácia". lol

![image](https://user-images.githubusercontent.com/11409143/66275661-29bf1e80-e88b-11e9-8d86-099eee771de0.png)

Podla blame to tak je uz 3 roky. :)

**Comment by mhozza** [comment]
Vyzera ze sa to pokazilo ked som odmazal tie fuzzy veci, ktore sposobovali ze sa to nepouzilo.
