### ISSUE TITLE
Prerátanie levelov nezbehlo správne

### ISSUE THREAD

**Issue by david58** [trojsten/web#1274]
spúšťaný command bol: `python manage.py ksp_update_levels camp 41`
a result je, že 6 účastníkom sústredka sa neupdatol level.
Tento krát som ich pridal ručne, ale zišlo by sa to fixnúť do konca 2. kola zimnej časti.

**Comment by ano95** [comment]
Skript sa spolieha, ze pocas campu bezalo kolo -> takze v pripade minuleho rocnika to pocitalo so zlymi vysledkovkami.
