### ISSUE TITLE
Assignment of points fails if only small hint exists

### ISSUE THREAD

**Issue by michalstanik1** [trojsten/web#1402]
https://github.com/trojsten/web/blob/9efa964e47c8750861f06e2298e98fc9c79b57a5/trojsten/rules/susi.py#L213

If only small hint exists and big hint does not, after the date of big hints the points for the small hint are not correctly deduced because none of these conditions is fulfilled.

**Comment by milos7250** [comment]
Fixed by the commit above, which will get merged to main with other Susi changes.
