### ISSUE TITLE
Freezovanie vysledkoviek

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#241]
Aktualne sa vysledkovka generuje velmi dynamicky. To znamena, ze ked si clovek zmeni udaje (napr. rocnik) alebo pojde do dalsieho rocnika, tak sa to zmeni vo vsetkych vysledkovkach. Ked zmaturuje, tak vo vsetkych zmizne.
Bolo by dobre vysledkovku ked bude finalna zmrazit a uchovat v tom stave navzdy. Toto by potom mohlo indikovat aj to, ze vysledkovka je finalna ( #138  )

**Comment by maaario** [comment]
@mhozza spravil v #1123
