### ISSUE TITLE
API & shit pre externe ulohy (napr. zwarte doos)

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#245]
- ulahcit vyrabanie prikladov ako je zwarte doos
  - hlavne nejake submitovacie API
    - submit konkretnej ulohy
    - zistit ci je clovek veduci k danej ulohe
    - zistit ci je uloha verejna
- zachovat dizajnovu identitu stranky aj v tychto ulohach
- zamedzit chybam a nestabilitam stranky v tychto ulohach
- umoznit externym uloham bezat na inom servri
  - nejaky login protocol (napr. openid)
  - nejaky submit protokol
- zistit ci dokazeme spravit nejake rozumne bezpecne ajax submitovanie (najlepsie ak bude mozne mat aj client side testovac, ale to asi bez server testovaca,ktory to este znovu overi nepojde)

**Comment by mhozza** [comment]
Toto asi zavrem, nove veci budu zvlast weby a API sa bude pisat podla potreby. Nieco uz mozno aj mame.

**Comment by maaario** [comment]
Hej, mame API na login + external submit token na posielanie submitov.
