### ISSUE TITLE
Ankety

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#252]
- vseobecne ankety
- budu sa pouzivat na rozne ucely
  - sustredka, veci na stranke...
- bolo by pekne mat nejaky slusny interfejs na vyrabanie ankety, s moznostu zrecyklovania nejakej starej ankety (skopiruju sa otazky)

Model pre anketu:
- nazov
- dedlajn

Model pre otazku:
- ID ankety (kazda otazka patri prave jednej ankete, aby na to mohla byt naviazana odpoved)
- nazov
- typ odpovede (vsetky odpovede budu pre jednoduchost stringy, toto sluzi len na zobrazenie spravneho widgetu)

Model pre odpoved:
- id otazky
- id uzivatela
- odpoved (vo forme stringu)

**Comment by gardenerik** [comment]
#1309
