### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#386]
Dashboard pre ucastnika a veduceho

Ucastnicky by mal obsahovat:
- Aktualne sutaze:
  - linky na zadania a vysledky aktualneho kola pre jednotlive sutaze
  - datum konca kola
- novinky (staci cca 5 najnovsich)

Veducovsky
- link na opravovanie aktualneho prikladu ku ktoremu je priradeny
- najeke dalsie uzitocne linky
- novinky - tak ako user

**Comment by ano95** [comment]
Keďže pre vedúceho budú tie wizardy jedného dňa ^, zatiaľ ten pre účastníkov.

- Kde to chceme mať? Rozmýšľal som nad rootom loginu, keďže aktuálne tam je len nápis "Tu budú dlaždice, pre každú podstránku/súťaž bežiacu pod trojstenom"

Vyzerať by to mohlo nejako takto:
![dash](https://user-images.githubusercontent.com/11409143/56977607-d75c3200-6b75-11e9-9ce5-676c0a5db38d.png)

**Comment by mhozza** [comment]
Idea bola nahradit tym stranku s novinkami (teda ta by ostala ale nebola by home page).

Hore by bol ten progessbar a nejake velke buttony na zadania/vzoraky/vysledky. Ksp mavalo 2 sutaze KSP a KSP-T. Ale uz tusim 2 roky KSP-T nebolo, tak to netreba nejak extra riesit.

Podtym asi top 5 noviniek (mozno novsie ako 3 mesiace) a linku na stranku so vsetkymi novinkami. 


To co si navrhol vyzera tiez zaujimavo, ale na tu stranku imho chodi minimum ludi, takze to nie je take dolezite.

**Comment by ano95** [comment]
Takže v podstate len dostať progressbar a buttony na aktuálnu homepage?

**Comment by mhozza** [comment]
No niečo také. Teda momentálne tabpo prihlásení presmeruje na novinky. Po
novom by ťa mal presmerovať na dashboard = progessbar s novinkami.

**Comment by ano95** [comment]
@mhozza, aktuálne ťa to po prihlásení presmeruje späť na stránku, kde si bol pred tým. :thinking: ako by si sa teda dostal na nástenku?

**Comment by mhozza** [comment]
Homepage po prihlaseni je novinky (zobrazi sa ked navstivis ksp.sk, alebo
ked kliknes logo). Pred prihlasenim uvidis klasicky homepage.

Michal Hozza

**Comment by mhozza** [comment]
Tu je zodpovedny kod:
https://github.com/trojsten/web/blob/master/trojsten/views.py#L16

**Comment by ano95** [comment]
Aha, takto to je myslené. Tak to už hej.

**Comment by ano95** [comment]
V tom pripade by som to asi mal, vyzeralo by to nejako takto, ak nikto nema lepsie navrhy:

![image](https://user-images.githubusercontent.com/11409143/57029785-0d1b1c80-6c43-11e9-8844-6c9be994f56c.png)

A teda zobrazovalo by sa to prihlasenym miesto noviniek.

**Comment by mhozza** [comment]
Vyzerá fajn. Dal by som aj tlačítko na zadania (redundancia nezaškodí).

**Comment by ano95** [comment]
@mhozza to 1. kolo, 1. cast ta posle na zadania. Tlačítka tam dáva show_buttons, do coho by som nerad vrtal (su to tie iste tlacidla ako na https://www.ksp.sk/ulohy/). Ale keby sme moc chceli, dá sa to samozrejme pridať

**Comment by mhozza** [comment]
Ok, whatever.
