### ISSUE TITLE
Kalendár

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#394]
Zišiel by sa kalendár udalostí (niečo také bolo, myslím, aj v starom webe)
- Boli by tam termíny, sústredká, akadémie... všetko čo by malo byť viditeľné pre účastníkov.
- Možno by nebolo odveci to mať nejako integrované s trojsten google kalendárom (aby sme nemali 2 kalendáre na to isté).
- Kalendár by sa mal zobrazovať aj v dashboarde (#386)

**Comment by gardenerik** [comment]
github.com/kockatykalendar

**Comment by david58** [comment]
možno by bolo fajn mať niekde na seminárových stránkach taký kalendárik vytiahnutý z kockatého kalendára pre daný odbor, aj keď neviem kam by sa to vošlo, ak nechceme obnoviť pravý stĺpček ako bol na old.ksp.sk :D možno tak na spod menu, ale to nedáva až tak zmysel, no každopádne by sme ten kockatykalendar mohli niekde aspoň nalinkovať :grinning: buď do menu, alebo kludne aj do horného menu, možno namiesto Trojsten stránky, ktorá pre riešiteľov možno nemá až tak zmysel

**Comment by gardenerik** [comment]
Je v menu.
