### ISSUE TITLE
UX 404 page

### ISSUE THREAD

**Issue by black3r** [trojsten/web#453]
momentalne, ked sa pokusim otvorit neexistujucu stranku (napr. www.ksp.sk/something ), su 3 moznosti
- som neprihlaseny a vybafne na mna login box.. why?
- som prihlaseny ako user a vybafne na mna Permission Denied
- som prihlaseny ako admin a vybafne na mna okienko s editaciou clanku

v prvych dvoch moznostiach by to podla mna chcelo zobrazit nejaku 404 stranku, v tretej moznosti mozno 404 stranku s tlacitkom vytvorit clanok?

also: ak nejaka app-ka vrati 404-ku, tak je nenastylovana (napr. stiahnutie vzorakov za user-a bez pristupu k nim, aktualne na https://www.ksp.sk/ulohy/solutions_pdf/4/ )

**Comment by mhozza** [comment]
duplicate #341
