### ISSUE TITLE
Znizit load time

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#483]
Nasa stranka sa nacitava relativne dlho

- [x]  zmensit obrazky v carouseli
- [ ]   vysledkovka sa dlho laduje
- ~~mozno chceme vypisovat/logovat load time~~ je to v analytics

todo dopisat sem a nalinkovat ostatne issues

**Comment by gardenerik** [comment]
Spomenuté veci sa podľa všetkého vyriešili, výsledkovka #595.
