### ISSUE TITLE
Upratať po celery

### ISSUE THREAD

**Issue by black3r** [trojsten/web#496]
treba:
- [ ] spravit konfigurovatelne meno appky
- [ ] pridat citanie dotenv 
- [ ] rozbehat demona pre web
- [ ] zistit ci vie jeden demon obsluhovat 2 worker-ov a ak hej tak aj worker-a pre betu
- [ ] zistit ako sa da rozumne restartovat worker pri update bez root-ovskych prav

**Comment by mhozza** [comment]
Celery sme zapalili.
