### ISSUE TITLE
Automaticky generovane novinky po zverejneni zadani, uloh...

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#505]
Ked sa nastavia zadania/vzoraky na vyditelne, mohla by sa automaticky vygenerovat novinka (aj s potrebnymi linkami).
Asi chchceme mat mzonost tuto feature aj vypnut.

**Comment by gardenerik** [comment]
Deckam pride notifikacia o kole, automaticky generovane novinky by vyzerali ako scam web.
