### ISSUE TITLE
Podpora jednoduchych variables na strankach ako Organizatori/FAQ/Pravidla....

### ISSUE THREAD

**Issue by jablkoj** [trojsten/web#609]
Obcas mame na strankach pisane texty typu "KSP existuje uz 32 rokov"
Takyto text sa kazdy rok stane neakutalny. Zislo by sa pre to spravit nejaka podpora, nejake makra typu, aby sa dalo pisat:
`KSP existuje uz [variable thisyear-1982] rokov`. (ale aby to nejak ratalo roky od septembra)
alebo:
`KSP existuje uz [variable rocnik] rokov.` (kde rocnik by sa tahal dako z DB alebo niecoho).
alebo nieco.

**Comment by gardenerik** [comment]
<script>document.write()</script> a aj tak ukazujeme datum upravy, so s tymto by to bolo divne
