### ISSUE TITLE
Moznost mat fotku v profile.

### ISSUE THREAD

**Issue by jablkoj** [trojsten/web#611]
Stranky su ovela veselsie, ked tam maju lodia aj nejake profilovky. Tie by sa mohli zobrazovat v diskusnych forach ale napriklad aj vo verejnych profiloch ludi (ak take nieco bude #610).

Taktiez ak chceme mat veselsi zoznam organizatorov, tak fotky tomu pomozu (po vzore FKS).

Asi to nechce byt priamo v modeli cloveka (ktovie), ale ako pridavna vlasnost (podbne ako je COP), treba hlavne vyriesit, ako sa to bude ukladat ako subory a ako to bude reprezentovane v DB.

**Comment by mhozza** [comment]
Obsolete
