### ISSUE TITLE
Povedat ucastnikom co maju robit ak maju nejaky problem.

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#630]
Udrbali sme diskusie zo zadani, ale nepridali sme ziaden iny sposob ako reportovat problemy. Chcelo by to bud dat tam aspon mailto link, alebo urobit send formular, ktory message obali sympatickymi vecami ako napr. linka na priklad na ktory sa dotycny stazuje, pekny subject...

P.S. ani vseobecne diskusie momentalne nemame.

**Comment by gardenerik** [comment]
Ak je problém, treba sa obrátiť na seminár, ktorý túto informáciu niekde zverejní, obvykle na stránke "kontakt".
