### ISSUE TITLE
Pridať do databázy nejaký display-name (prezývku)

### ISSUE THREAD

**Issue by sesquideus** [trojsten/web#654]
Aby sa napríklad pri novinkách nezobrazoval login, ale niečo pekné.

**Comment by dodo42** [comment]
Čo tak len proste pridať do User modela field `alias` a podľa neho by sa v novinkách zobrazovalo:
- meno a priezvisko, keď je alias prázdny,
- prezývka, ak ju vedúci má vyplnenú, pričom celé meno sa môže ukázať pri nadídení myšou.

**Comment by maaario** [comment]
Keďže novinky sú externá appka, tak to asi nepôjde veľmi pekne ...

**Comment by mhozza** [comment]
Akoze dalo by sa vyhackovat, ale podla mna login alebo meno je ok v novinkach.
Zavrem to, nech robime dolezitejsie veci.
