### ISSUE TITLE
nedostupny testovac hodi 500

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#666]
Ked je zle nakonfigurovany testovac, hodi to standardny 500 error.
Chceme:
- uzivatelovi slusne povedat ze sa nepodarilo submitnut (idealne automaticky dotestovat ked bude testovac naspat bezat)
- vynadat veducim ze testovac je rozdrbany (idealne iba raz) a treba ho fixnut.

**Comment by maaario** [comment]
#duplicate 1097
v 1097 je to ale lepšie spísané, tak toto zatváram
