### ISSUE TITLE
chybajuca dokumentacia

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#668]
Web nemá prakticky žiadnu dokumentáciu.
Chcelo by to aspoň spomenúť základnú štruktúru webu - kde sú nastavenia, ako sa overridujú, ako fungujú niektoré zložitejšie veci, ako sa to deployuje updatuje a podobne. Momentálne o týchto veciach tušia tak 3ja ľudia, z toho 1 sa chystá do dôchodku.

**Comment by mhozza** [comment]
Kubik cosi spisal tusim.

**Comment by maaario** [comment]
@kubik369 ?
