### ISSUE TITLE
Preklopit akademia web

### ISSUE THREAD

**Issue by black3r** [trojsten/web#717]
- Bude sa mergovat akademia do trojstenweb-u 
- Co najrozumnejsie zmigrovat existujuce appky a modely
- Akademie a kluby mergovat do sustrediek
- Migrovat userov aby ostali statistiky
- Snazit sa ponechat vsetky features tak jak su
- Skusit spravit hromadnu korespondenciu (asi formou exportu emailov do mailchimpu)

**Comment by gardenerik** [comment]
Out of scope.
