### ISSUE TITLE
Nepoužívané prihlasovátko na akcie

### ISSUE THREAD

**Issue by syslo** [trojsten/web#881]
Prihlasovací systém na akcie a častokrát potom ani samotné akcie sa nepoužívajú, z niekoľkých dôvodov:
- nepodporuje GForms funkcie ako napríklad conditional jumps, ktoré sa často používajú.
- je previazaný na dodatočné vlastnosti a vytvára v nich chaos (mal by podporovať aj dodatočné vlastnosti (veľkosť trička, mobil) ale aj vlastnosti špecifické pre akciu (meno matky za slobodna, obľubený programovací jazyk, ...)
- akcia má iba jednu prihlášku, UFOPrask potrebuje minimálne 2 (alebo conditional jumps)
- akcia má foreign key na prihlášku, aj keď, podľa mňa, prihláška by mala mať FK na akciu - teda najskôr vytvoríme akciu až potom prihlášku.

Treba premyslieť, čo s týmto systémom. Tiež treba ešte pred migráciou akcií schovať nepotrebné fieldy a 
prípadne spraviť zmeny modelov, ktoré by sa potom ťažko migrovali.

**Comment by mhozza** [comment]
Asi je to najlepsie spravit nanovo.
