### ISSUE TITLE
Prekopat adresy pouzivatela

### ISSUE THREAD

**Issue by mhozza** [trojsten/web#884]
momentalne ma uzivatel moznost si pridat adresu domov a korespondencnu adresu, s tym ze adresa domov je povinna.

Navrhujem aby nameisto toho aby bolo vo formulari vyplnenie adresy, umoznime uzivatelovi vo formulari stlacit tlacitko pridat adresu, ktore mu umozni pridat adresu lubovolneho typu (zatial bud home alebo mailing) a lubovolne vela adries.

Teda umozni to tieto veci:
- mat 0 adries
- mat mailing adresu aj ked nemas home adresu
- mat ulozenych viac adries ked to nahodou dany clovek potrebuje (napr. cez prazdniny byva inde ako cez skolsky rok, alebo nieco)

Navyse si uzivatel bude moct vybrat najviac 1 adresu kam mu budeme posielat postu.

Pre aktualne modely by to znamenalo len ze sa prida field `type` do adresy (pripadne este unique_together field `primary`, ale to by som mozno riesil zvlast) a user nebude mat 2 adresy ale 1 m2m field na adresu.

related #66

**Comment by maaario** [comment]
Existuje bool field pre korešp. na školu a bolo by treba checkovať, či už nemá užívateľ zaškrtnuté to.

Po #1154 bude adresa nepovinná, a ak bude povinná pre nejakú súťaž, bude povinná len jedna korešpondenčná. Umožní sa tak mať 0 adries a mať len korešpondenčnú.

Momentálne má trojstenweb 2000 používateľov, 67 má mail to school, 26 používa korešpondenčnú adresu - podľa mňa je tak zbytočné mať viac korešpondenčných adries.

Po #1154 teda toto navrhujem zavrieť.

**Comment by mhozza** [comment]
Takze adresu domov vyhodime prec a budeme mat bud korespondencnu alebo ziadnu.
