### ISSUE TITLE
Vytvoriť staging pre opravovania

### ISSUE THREAD

**Issue by kubik369** [trojsten/web#972]
Opravovania by malo byť možné nahrať a až následne zverejniť, aby mohol napr. skúsenejší vedúci najskôr skontrolovať opravené riešenia niekoho kto sa zaúča.

**Comment by gardenerik** [comment]
ak nie je zapnute zobrazovanie bodov vo vysledkovke, nezobrazuje sa ani opravenie

**Comment by peter-ralbovsky** [comment]
A nezobrazuje sa ani opraveny submit, ked si stiahne popis?

**Comment by gardenerik** [comment]
Malo by to tak byť, aspoň podľa tohto:

https://github.com/trojsten/web/blob/4dd33f840d2c6ede30053dbec6547c92c1e4b40f/trojsten/submit/templatetags/submit_parts.py#L47

**Comment by peter-ralbovsky** [comment]
Ok, len si pamatam na to nejaku issue.
